### ISSUE TITLE
How to run this in PHP?

### ISSUE THREAD

**Issue by orynider** [MarcelWaldvogel/autosubset#1]
I have something like this:

		$cmd =" /usr/bin/pyftsubset --unicodes="'. implode(',', $unicodes).'" --output-file="'.$outFile.'"';

**Comment by MarcelWaldvogel** [comment]
If you already have extracted the unique code points you use, then there is no need to run autosubset, as it does the same thing.

For the actual PHP command: Do you have the input available as a file (easy: `$cmd = "autosubset FONT < " . $inFile . " > " . "$outFile"`; be sure that the file names have no spaces or shell-metacharacters in them, as usual) or as a string?

**Comment by orynider** [comment]
Thank You! I renamed the project github.com/BeitDina/webfont/ and ATM is working OK.
